task :default => [:patterns, :ie] do
 puts "Running both compass scss-main and scss-ie"
 sh %(sh tail -f patterns/nohup.out -f ie-styles/nohup.out)
end

desc "Watch scss-main compass project"
task :patterns do
    sh %(cd scss-main/; nohup sh Watchfile &)
end

desc "Watch scss-ie compass project"
task :ie do
    sh %(cd scss-ie/; nohup sh Watchfile &)
end

# ensure that each shell script spawns a new process
# tail both files to watch what's going on `tail -f patterns/nohup.out -f ie-styles/nohup.out`