task :default => [:patterns, :ie] do
 puts "Running both compass patterns and ie"
 sh %(sh tail -f patterns/nohup.out -f ie-styles/nohup.out)
end

desc "Watch patterns compass project"
task :patterns do
    sh %(cd patterns/; nohup sh Watchfile &)
end

desc "Watch ie compass project"
task :ie do
    sh %(cd ie-styles/; nohup sh Watchfile &)
end

# ensure that each shell script spawns a new process
# tail both files to watch what's going on `tail -f patterns/nohup.out -f ie-styles/nohup.out`